version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2023-09-07T02-05-02Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=raw,bronze,silver,gold
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  spark:
    build: ./docker/spark
    volumes:
      - ./artifacts:/tmp/artifacts
      - ./docker/spark/etl_pipeline.py:/app/etl_pipeline.py
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark:7077
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      minio:
        condition: service_healthy

  mlflow:
    build: ./docker/mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./docker/mlflow:/app
    working_dir: /app
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      minio:
        condition: service_healthy

  fastapi:
    build: ./docker/fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./docker/fastapi:/app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  streamlit:
    build: ./docker/streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./docker/streamlit:/app
    depends_on:
      - fastapi

networks:
  default:
    driver: bridge

volumes:
  minio_data: {}